 export const LOAD_PHOTOS = 'LOAD_PHOTOS'
 export const LOAD_PHOTOS_SUCCESS = 'LOAD_PHOTOS_SUCCESS'
 export const LOAD_PHOTOS_ERROR = 'LOAD_PHOTOS_ERROR'

 export const LOAD_SINGLE = 'LOAD_SINGLE'
 export const LOAD_SINGLE_SUCCESS = 'LOAD_SINGLE_SUCCESS'
 export const LOAD_SINGLE_ERROR = 'LOAD_SINGLE_ERROR'
